{% set name = "csdms-topoflow-channels-dynamic-wave" %}
{% set version = "3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/topoflow-bridge

requirements:
  build:
    - bmi-babel
    - topoflow
    - isl <=0.12.2
  run:
    - bmi-babel
    - topoflow
    - isl <=0.12.2

test:
  requires:
    - pymt
    - bmi-tester
